builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    binary: litter-exporter
dockers:
  - image_templates:
    - tlkamp/litter-exporter:{{ .Tag }}
    - tlkamp/litter-exporter:latest
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^style:'
