{
 "title": "Litter Robot",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "name",
    "query": {
     "query": "label_values(litterrobot_capacity, name)"
    }
   },
   {
    "name": "id",
    "label": "id",
    "query": {
     "query": "label_values(litterrobot_capacity{name=\"$name\"}, id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Unit Status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "litterrobot_unit_status{id=\"$id\"}"
    }
   ]
  },
  {
   "title": "Drawer Fullness",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "litterrobot_cycles{id=\"$id\"} / litterrobot_capacity{id=\"$id\"}"
    }
   ]
  },
  {
   "title": "Cycles",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(litterrobot_cycles{id=\"$id\"}[1d])",
     "legendFormat": "Cycles"
    }
   ]
  }
 ]
}