name: Release
on:
  workflow_run:
    workflows:
      - Test
    branches:
      - main
    types:
      - completed

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
      - env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          npx -p @semantic-release/changelog -p @semantic-release/git -p semantic-release semantic-release
