name: Test
on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test
        run: go test -v ./...

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2

  goreleaser-check:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: actions/setup-go@v3
          with:
            go-version: 1.18
        - uses: goreleaser/goreleaser-action@v2
          with:
            args: check

  release-dry-run:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Release Dry Run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx -p @semantic-release/changelog -p @semantic-release/git -p semantic-release \
          semantic-release -d --branches ${GITHUB_REF##*/}
